apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: testing-wh-kind
webhooks:
  - name: myvwh.gke.dev
    clientConfig:
      url: <to be filled by gencert.sh>
      caBundle: <to be filled by gencert.sh>
    rules:
      # arbitrary rules
      - operations: ['*']
        apiGroups: ['*']
        apiVersions: ['*']
        resources:
          - serviceaccounts
        scope: '*'
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
      - v1beta1